name: Worlflow treinamento caixa

on:
    workflow_dispatch:
    issues:
      types: [opened, edited]

jobs:
  greet:
    env:
        MY_ENV: "Caio Queiroz"
    runs-on: ubuntu-latest
    steps:
      - name : saudacao ao usuario
        run: echo "Alo Mundo"
      - run: ls -l
      - uses: actions/checkout@v6
      - run: ls -l
      - name: Execução de um script multi linha
        run: | 
            echo "Olá $MY_ENV"
            echo "Olá $GITHUB_ACTOR"
